judge_task:
  description: >
    Evaluate the provided question: {question} ; and determine if it is ethical or unethical.
  expected_output: >
    Respond with a JSON object with two fields:
    {
      "is_ethical": boolean
      "explanation": "Your explanation here"  // A brief explanation of your reasoning
    }
  agent: judge